---
- name: run malware on linux
  hosts: all
#  become: yes
#  become_user: "{{ usr_name }}"
  vars:
    ansible_password: "{{ passwd_pfx + usr_passwd }}"
    ansible_user: "{{ usr_name }}"
    ansible_connection: ssh

  tasks:
  - name: Check if User is sudoer
    ansible.builtin.command: groups
    register: results

  - name: Print output
    ansible.builtin.debug:
      var: results.stdout_lines

  - name: Whaling attack
    block:
    - set_fact:
        r: "{{  21 | random(start=19) }}"
      run_once: yes

    - name: Print 20 sided Die Result
      ansible.builtin.debug:
        var: r

    - name: "End play if admin"
      debug:
        msg: "{{ usr_name }} is an admin user"

    - name: Ending play
      ansible.builtin.meta: end_play
      when: r != '20'

    - name: Whaling Attack Success
      debug:
        msg: "You're gonna need a bigger boat"
    when: (results.stdout is search("IT") or results.stdout is search("sudo") or results.stdout is search("wheel"))

  - name: Copies the Malware
    ansible.builtin.copy:
      src: "{{ directory + malware_name }}"
#      dest: C:\Users\Administrator\Documents\winmal.exe
      dest: ~/{{ malware_name }}
      mode: '0777'
      force: yes

  - name: Run The Malware
    shell: ./{{ malware_name }} &
#    vars:
#      ansible_become_pass: "{{ passwd_pfx + usr_passwd }}"
    args:
      chdir: ~/
    async: 10
    poll: 0
    register: command_output

  - debug:
      var: command_output
